name: Run Shell Script

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x script.sh

      - name: Run Script
        run: ./script.sh
